name: PermissionEx-PM
main: permissionex\Main
author: xStrixU
version: 1.0
api: 3.0.0

permissions:
 pex.comand:
   default: op
   description: Allow to use all pex commands
   children:
     pex.command.general:
       default: op
       description: Allow to use general pex commands
     pex.command.set:
       default: op
       description: Allow to use set pex commands
     pex.command.users:
       default: op
       description: Allow to use general users commands
     pex.command.general:
       default: op
       description: Allow to use general groups commands